name: cliper
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/MashudiSudonym/cliper-youtube-video

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  interact: ^2.2.0
  dart_console: ^1.2.0
  youtube_explode_dart: ^2.5.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
